export const SPORTS_CONFIG = {
  Football: {
    type: "Team Sport",
    categories: [
      {
        id: "men",
        label: "Men's Team",
        minPlayers: 11,
        maxPlayers: 15,
        eventID: 3,
        prizePool: 15000,
        registrationFee: 4500,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
      {
        id: "women",
        label: "Women's Team",
        minPlayers: 8,
        maxPlayers: 12,
        eventID: 4,
        prizePool: 12000,
        registrationFee: 2500,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
    ],
  },
  Cricket: {
    type: "Team Sport",
    categories: [
      {
        id: "men",
        label: "Men's Team",
        minPlayers: 11,
        maxPlayers: 15,
        eventID: 1,
        prizePool: 15000,
        registrationFee: 4500,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
      {
        id: "women",
        label: "Women's Team",
        minPlayers: 8,
        maxPlayers: 12,
        eventID: 2,
        prizePool: 12000,
        registrationFee: 2500,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
    ],
  },
  Basketball: {
    type: "Team Sport",
    categories: [
      {
        id: "men",
        label: "Men's Team",
        minPlayers: 5,
        maxPlayers: 9,
        eventID: 9,
        prizePool: 9000,
        registrationFee: 3000,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
      {
        id: "women",
        label: "Women's Team",
        minPlayers: 5,
        maxPlayers: 9,
        eventID: 10,
        prizePool: 9000,
        registrationFee: 2000,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
    ],
  },
  Volleyball: {
    type: "Team Sport",
    categories: [
      {
        id: "men",
        label: "Men's Team",
        minPlayers: 6,
        maxPlayers: 9,
        eventID: 7,
        prizePool: 9000,
        registrationFee: 3000,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
      {
        id: "women",
        label: "Women's Team",
        minPlayers: 6,
        maxPlayers: 9,
        eventID: 8,
        prizePool: 9000,
        registrationFee: 2000,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
    ],
  },
  "Lawn Tennis": {
    type: "Team Entry",
    categories: [
      {
        id: "men_singles",
        label: "Men (Singles)",
        minPlayers: 1,
        maxPlayers: 1,
        eventID: 16,
        prizePool: 2000,
        registrationFee: 399,
        feeUnit: "per_head",
        notes: "",
        teamNameRequired: false,
      },
      {
        id: "women_singles",
        label: "Women (Singles)",
        minPlayers: 1,
        maxPlayers: 1,
        eventID: 17,
        prizePool: 2000,
        registrationFee: 399,
        feeUnit: "per_head",
        notes: "",
        teamNameRequired: false,
      },
      {
        id: "group_men",
        label: "Group (Men)",
        minPlayers: 4,
        maxPlayers: 4,
        eventID: 118,
        prizePool: 5000,
        registrationFee: 1599,
        feeUnit: "team",
        notes: "4 team members",
        teamNameRequired: true,
      },
      {
        id: "group_women",
        label: "Group (Women)",
        minPlayers: 4,
        maxPlayers: 4,
        eventID: 119,
        prizePool: 5000,
        registrationFee: 1599,
        feeUnit: "team",
        notes: "4 team members",
        teamNameRequired: true,
      },
    ],
  },
  Badminton: {
    type: "Team Entry",
    categories: [
      {
        id: "men",
        label: "Men's Team",
        minPlayers: 3,
        maxPlayers: 6,
        eventID: 11,
        prizePool: 6000,
        registrationFee: 2500,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
      {
        id: "women",
        label: "Women's Team",
        minPlayers: 3,
        maxPlayers: 6,
        eventID: 12,
        prizePool: 6000,
        registrationFee: 1500,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
    ],
  },
  "Table Tennis": {
    type: "Mixed",
    categories: [
      {
        id: "men_team",
        label: "Men (Team)",
        minPlayers: 3,
        maxPlayers: 5,
        eventID: 18,
        prizePool: 4000,
        registrationFee: 1200,
        feeUnit: "team",
        notes: "Team",
        teamNameRequired: true,
      },
      {
        id: "women_team",
        label: "Women (Team)",
        minPlayers: 3,
        maxPlayers: 5,
        eventID: 19,
        prizePool: 4000,
        registrationFee: 1000,
        feeUnit: "team",
        notes: "Team",
        teamNameRequired: true,
      },
      {
        id: "men_single",
        label: "Singles (Men)",
        minPlayers: 1,
        maxPlayers: 1,
        eventID: 20,
        prizePool: 2000,
        registrationFee: 400,
        feeUnit: "team",
        notes: "",
        teamNameRequired: false,
      },
      {
        id: "women_single",
        label: "Singles (Women)",
        minPlayers: 1,
        maxPlayers: 1,
        eventID: 21,
        prizePool: 2000,
        registrationFee: 300,
        feeUnit: "team",
        notes: "",
        teamNameRequired: false,
      },
      {
        id: "mixed",
        label: "Mixed",
        minPlayers: 2,
        maxPlayers: 2,
        eventID: 22,
        prizePool: 3000,
        registrationFee: 500,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
    ],
  },
  Carrom: {
    type: "Mixed",
    categories: [
      {
        id: "men_team",
        label: "Men",
        minPlayers: 3,
        maxPlayers: 5,
        eventID: 23,
        prizePool: 1500,
        registrationFee: 499,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
      {
        id: "women_team",
        label: "Women",
        minPlayers: 3,
        maxPlayers: 5,
        eventID: 24,
        prizePool: 1500,
        registrationFee: 499,
        feeUnit: "team",
        notes: "",
        teamNameRequired: true,
      },
      {
        id: "mixed_double",
        label: "Mixed Doubles",
        minPlayers: 2,
        maxPlayers: 2,
        eventID: 25,
        prizePool: 1000,
        registrationFee: 499,
        feeUnit: "team",
        notes: "Fixed team size",
        teamNameRequired: true,
      },
    ],
  },
  Chess: {
    type: "Team Entry",
    categories: [
      {
        id: "open",
        label: "Open",
        minPlayers: 5,
        maxPlayers: 6,
        eventID: 5,
        prizePool: 5000,
        registrationFee: 1200,
        feeUnit: "team",
        notes: "5 + 1 (optional) members",
        teamNameRequired: true,
      },
    ],
  },
  "E-Sports": {
    type: "E-Sports",
    categories: [
      {
        id: "bgmi",
        label: "BGMI Team",
        minPlayers: 4,
        maxPlayers: 4,
        eventID: 13,
        prizePool: 8000,
        registrationFee: 299,
        feeUnit: "team",
        notes: "Fixed squad",
        teamNameRequired: true,
      },
      {
        id: "free_fire",
        label: "Free Fire Team",
        minPlayers: 4,
        maxPlayers: 4,
        eventID: 15,
        prizePool: 6000,
        registrationFee: 199,
        feeUnit: "team",
        notes: "Fixed squad",
        teamNameRequired: true,
      },
      {
        id: "valorant",
        label: "Valorant Team",
        minPlayers: 5,
        maxPlayers: 5,
        eventID: 14,
        prizePool: 6000,
        registrationFee: 299,
        feeUnit: "team",
        notes: "Fixed squad",
        teamNameRequired: true,
      },
    ],
  },
};
